#pragma once

enum LOADINGID { LOADING_TITLE, LOADING_TUTORIAL, LOADING_MAINLOBBY , LOADING_DUNGEONLOBBY,LOADING_REGEN,LOADING_SHOP, LOADING_POT, LOADING_BOSS1, LOADING_BOSS2, LOADING_NORMAL, LOADING_END };
enum WINMODE { MODE_FULL, MODE_WIN };
enum SCENE_TYPE{ SCENE_TITLE, SCENE_TUTORIAL, SCENE_MAINLOBBY, SCENE_DUNGEONLOBBY,SCENE_REGEN, SCENE_SHOP, SCENE_BOSS1 , SCENE_BOSS2, SCENE_POT, SCENE_NORMAL, SCENE_END};

enum OBJ_TYPE { OBJ_PLAYER, OBJ_APOSTLE_NIGHT, OBJ_APOSTLE_MEMORY, OBJ_APOSTLE_COURAGE, OBJ_BOSS, OBJ_MONSTER, OBJ_ARROW, OBJ_CHARGE_ARROW, OBJ_SKILL ,OBJ_BULLET, OBJ_LANDSCAPE, OBJ_SPECIAL, OBJ_END };

enum ClAWDIR { CLAW_LEFT, CLAW_RIGHT }; // 원 혼자 씀 쏘리

enum SPEC_OBJ_TYPE { SOBJ_PLAYER, SOBJ_BOSS, SOBJ_MONSTER, SOBJ_ARROW, SOBJ_END };

enum DELETE_TYPE{ NON_DELETE , OK_DELETE };

enum ITEM_TYPE { ITEM_STATUS, ITEM_WEAPON, ITEM_ACC, ITEM_END }; //준석
// ITEM_STATUS : 착용되지않는 스테이터스에만 영향을 주는 소모품
// ITEM_WEAPON : 착용이 가능한 무기 류 아이템
// ITEM_ACC : 착용이 가능한 악세사리 류 아이템
enum INTERACT_TYPE { INTER_BUTTON, INTER_DIALOG, INTER_ITEM_INFO, FIELD_ITEM_INFO, INTER_END };
enum INTERACT_TARGET { TARGET_ITEM_DROP, TARGET_ITEM_SHOP, TARGET_SUPPLYCREW, TARGET_BLACKSMITH, TARGET_APOSTLE_COURAGE, TARGET_APOSTLE_NIGHT, TARGET_APOSTLE_TIME
						,TARGET_REGEN_STONE, TARGET_POT, TARGET_RABBIT_BLUE, TARGET_RABBIT_PINK, TARGET_SUPPLY_BIGCAT, TARGET_SUPPLY_BACKPACK, TARGET_REROLL_REVER, TARGET_BUY_FALSE, TARGET_ROOTING_FALSE, TARGET_END};
enum MONEY_VARIATION { MONEY_INCREASE, MONEY_DECREASE, MONEY_END};
enum GEM_VARIATION { GEM_INCREASE, GEM_DECREASE, GEM_END };


enum APOSTLE_TYPE { TIME, COURAGE ,NIGHT, APOSTLE_END };

enum VIEW_TYPE { VIEW_BASIC, VIEW_FAR, VIEW_NEAR, VIEW_END };

enum BOW_TYPE { BOW_SYLPH, BOW_TIME, BOW_NIGHT, BOW_FIRE, BOW_END };

enum BOSS_NAME { BOSS_DOEWOLE, BOSS_DOCHEOL, BOSS_END };

enum ARROW_TYPE { ARROW_TYPE_SYLPH, ARROW_TYPE_CHARGE_SYLPH, ARROW_TYPE_TIME, ARROW_TYPE_TIME_CHARGE, ARROW_TYPE_NIGHT, ARROW_TYPE_NIGHT_CHARGE, ARROW_TYPE_FIRE, ARROW_TYPE_FIRE_CHARGE, ARROW_TYPE_END };;

namespace Engine
{
	// ID_DYNAMIC : 매 프레임마다 갱신을 해야하는 컴포넌트 집단
	enum COMPONENTID{ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO {INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };
	enum TEXTYPE { TEX_NORMAL, TEX_CUBE, TEX_END };
	enum RENDERID { RENDER_PRIORITY, RENDER_ALPHA, RENDER_NONALPHA, RENDER_ALPHATEST, RENDER_UI, RENDER_BLACK, RENDER_ALPHA_STATICOBJ, RENDER_TUTORIALUI, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum MONSTER_STATE { MONSTER_IDLE, MONSTER_MOVE, MONSTER_ATTACK, MONSTER_DEAD, MONSTER_END };
	enum MONSTER_HEAD { HEAD_FRONT, HEAD_BACK, HEAD_END };
	enum MONSTER_NAME { NAME_SLIME, NAME_SOUL, NAME_MUTATION, SOUL_BULLET, NAME_END };

	enum NPC_NAME { NPC_SUPPLYCREW, NPC_SUPPLYCREW_BACKPACK, NPC_SUPPLYCREW_BIGCAT, NPC_BLACKSMITH, NPC_APOSTLE_TIME, NPC_APOSTLE_COURAGE, NPC_APOSTLE_NIGHT, NPC_RABBIT_BLUE, NPC_RABBIT_PINK, 
					NPC_SUPPLY_BIGCAT, NPC_SUPPLY_BACKPACK, NPC_REROLL_REVER, NPC_REGEN_STONE, NPC_POT, NPC_END };

	enum BULLET_STATE { BULLET_IDLE, BULLET_MOVE, BULLET_END };

	enum UI_CATEGORY { UI_NONE, UI_MENU, UI_FRONT, UI_END };

	enum FOOT_TYPE { FOOT_TYPE_WATER, FOOT_TYPE_SMOKE, FOOT_TYPE_END };

	enum COLLIDER_TYPE { COLLIDER_STATIC, COLLIDER_DYNAMIC, COLLIDER_END };
}

enum LANDSCAPE_TYPE { STATIC_OBJ, DYNAMIC_OBJ };
enum STATIC_OBJECT_ID { MAIN_LOBBY, BOSS_DOWOLE_OBJ, REGEN_OBJ, TUTORIAL_OBJ, DUNGEONLOBBY_OBJ, SHOP_OBJ, JARMAP_OBJ, NORMAL_OBJ, STATIC_OBJ_END };
enum DYNAMIC_OBJECT_ID {
	BUSH1, BUSH2, BUSH3, BUSH4, BUSH5,
	BUSH_FLOWER1, BUSH_FLOWER2,
	THORN1, THORN2, THORN3, THORN4, THORN5, THORN6,
	JAR_OBJ,
	STONE_WALL1, STONE_WALL2, INFECTION_WALL2,
	PILLAR1, PILLAR2, PILLAR4,
	DOOR, FLOATING, TEMPLE1, DOOR_HEAD, DOOR_PILLAR, DOOR_PILLAR2, DOOR_FIRE_BOSS, DOOR_SIDEDOOR,
	DOOR_HEAD_NORMAL, DOOR_PILLAR_NORMAL, DOOR_PILLAR2_NORMAL, DOOR_FIRE_NORMAL,
	HISTORIC_FLOATING, HISTORIC_SHINING1, HISTORIC_SHINING2, HISTORIC_SHINING3,
	OPENJAR_CENTER, OPENJAR_BODY, OPENJAR_HEAD,
	TEMPLE_BODY, TEMPLE_HEAD,
	DYNAMIC_OBJ_END
};

enum TERRAIN_TYPE { TERRAIN_BOSS_DOEWOLE,TERRAIN_MAINLOBBY,TERRAIN_REGEN, TERRAIN_TUTORIAL, TERRAIN_DUNGEONLOBBY, TERRAIN_JAR, TERRAIN_NORMAL, TERRAIN_TYPE_END };

enum BIRTH_EFFECT { BIRTH_LANDMARK, BIRTH_CHARGE, BIRTH_SUMMON, BIRTH_DONE, BIRTH_END };

enum DEBRIS_TYPE {DEBRIS_STONE, DEBRIS_JAR, DEBRIS_THORN, DEBRIS_END};

